[2024-08-20T10:11:24.984+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Vehicle_Data_scrape_Pipeline_3.scrape_post_links manual__2024-08-20T10:09:56.234460+00:00 [queued]>
[2024-08-20T10:11:24.991+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Vehicle_Data_scrape_Pipeline_3.scrape_post_links manual__2024-08-20T10:09:56.234460+00:00 [queued]>
[2024-08-20T10:11:24.992+0000] {taskinstance.py:2193} INFO - Starting attempt 3 of 4
[2024-08-20T10:11:25.002+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): scrape_post_links> on 2024-08-20 10:09:56.234460+00:00
[2024-08-20T10:11:25.007+0000] {standard_task_runner.py:60} INFO - Started process 1185 to run task
[2024-08-20T10:11:25.010+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Vehicle_Data_scrape_Pipeline_3', 'scrape_post_links', 'manual__2024-08-20T10:09:56.234460+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/vehicle_data_scraping_pipeline.py', '--cfg-path', '/tmp/tmpjd51_agy']
[2024-08-20T10:11:25.012+0000] {standard_task_runner.py:88} INFO - Job 10: Subtask scrape_post_links
[2024-08-20T10:11:25.046+0000] {task_command.py:423} INFO - Running <TaskInstance: Vehicle_Data_scrape_Pipeline_3.scrape_post_links manual__2024-08-20T10:09:56.234460+00:00 [running]> on host 8369baedd275
[2024-08-20T10:11:25.192+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='sdeshan' AIRFLOW_CTX_DAG_ID='Vehicle_Data_scrape_Pipeline_3' AIRFLOW_CTX_TASK_ID='scrape_post_links' AIRFLOW_CTX_EXECUTION_DATE='2024-08-20T10:09:56.234460+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-20T10:09:56.234460+00:00'
[2024-08-20T10:11:26.862+0000] {logging_mixin.py:188} WARNING -   0%|          | 0/4 [00:00<?, ?it/s]
[2024-08-20T10:11:26.866+0000] {logging_mixin.py:188} WARNING - 100%|##########| 4/4 [00:00<00:00, 41221.66it/s]
[2024-08-20T10:11:29.448+0000] {logging_mixin.py:188} WARNING -   0%|          | 0/11 [00:00<?, ?it/s]
[2024-08-20T10:11:29.449+0000] {logging_mixin.py:188} WARNING - 100%|##########| 11/11 [00:00<00:00, 75759.19it/s]
[2024-08-20T10:11:42.686+0000] {logging_mixin.py:188} WARNING -   0%|          | 0/24 [00:00<?, ?it/s]
[2024-08-20T10:11:42.687+0000] {logging_mixin.py:188} WARNING - 100%|##########| 24/24 [00:00<00:00, 88378.66it/s]
[2024-08-20T10:11:55.466+0000] {logging_mixin.py:188} WARNING -   0%|          | 0/24 [00:00<?, ?it/s]
[2024-08-20T10:11:55.467+0000] {logging_mixin.py:188} WARNING - 100%|##########| 24/24 [00:00<00:00, 95505.97it/s]
[2024-08-20T10:11:56.985+0000] {logging_mixin.py:188} WARNING -   0%|          | 0/5 [00:00<?, ?it/s]
[2024-08-20T10:11:56.986+0000] {logging_mixin.py:188} WARNING - 100%|##########| 5/5 [00:00<00:00, 43329.59it/s]
[2024-08-20T10:12:09.491+0000] {logging_mixin.py:188} WARNING -   0%|          | 0/4 [00:00<?, ?it/s]
[2024-08-20T10:12:09.495+0000] {logging_mixin.py:188} WARNING - 100%|##########| 4/4 [00:00<00:00, 41838.44it/s]
[2024-08-20T10:12:18.408+0000] {logging_mixin.py:188} WARNING -   0%|          | 0/1 [00:00<?, ?it/s]
[2024-08-20T10:12:18.415+0000] {logging_mixin.py:188} WARNING - 100%|##########| 1/1 [00:00<00:00, 11781.75it/s]
[2024-08-20T10:12:25.785+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/components/vehicle/data_scraping_components/post_links_extraction.py", line 68, in scrape_links
    upload_table('ikman_vehicle_post_links')
  File "/opt/airflow/dags/components/utils/database_table_creation.py", line 29, in upload_table
    cur.execute(f"""
psycopg2.errors.InsufficientPrivilege: could not open file "/var/lib/postgresql/csv/ikman_vehicle_post_links.csv" for writing: Permission denied
HINT:  COPY TO instructs the PostgreSQL server process to write a file. You may want a client-side facility such as psql's \copy.

[2024-08-20T10:12:25.803+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=Vehicle_Data_scrape_Pipeline_3, task_id=scrape_post_links, execution_date=20240820T100956, start_date=20240820T101124, end_date=20240820T101225
[2024-08-20T10:12:25.812+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 10 for task scrape_post_links (could not open file "/var/lib/postgresql/csv/ikman_vehicle_post_links.csv" for writing: Permission denied
HINT:  COPY TO instructs the PostgreSQL server process to write a file. You may want a client-side facility such as psql's \copy.
; 1185)
[2024-08-20T10:12:25.829+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-08-20T10:12:25.844+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
