[2024-08-21T04:07:46.513+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Vehicle_Data_scrape_Pipeline_5.scrape_post_links manual__2024-08-21T04:03:56.076722+00:00 [queued]>
[2024-08-21T04:07:46.521+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Vehicle_Data_scrape_Pipeline_5.scrape_post_links manual__2024-08-21T04:03:56.076722+00:00 [queued]>
[2024-08-21T04:07:46.522+0000] {taskinstance.py:2193} INFO - Starting attempt 4 of 4
[2024-08-21T04:07:46.533+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): scrape_post_links> on 2024-08-21 04:03:56.076722+00:00
[2024-08-21T04:07:46.537+0000] {standard_task_runner.py:60} INFO - Started process 681 to run task
[2024-08-21T04:07:46.540+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Vehicle_Data_scrape_Pipeline_5', 'scrape_post_links', 'manual__2024-08-21T04:03:56.076722+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/vehicle_data_scraping_pipeline.py', '--cfg-path', '/tmp/tmpa5ym0fwp']
[2024-08-21T04:07:46.541+0000] {standard_task_runner.py:88} INFO - Job 16: Subtask scrape_post_links
[2024-08-21T04:07:46.582+0000] {task_command.py:423} INFO - Running <TaskInstance: Vehicle_Data_scrape_Pipeline_5.scrape_post_links manual__2024-08-21T04:03:56.076722+00:00 [running]> on host 6bc55404d738
[2024-08-21T04:07:46.734+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='sdeshan' AIRFLOW_CTX_DAG_ID='Vehicle_Data_scrape_Pipeline_5' AIRFLOW_CTX_TASK_ID='scrape_post_links' AIRFLOW_CTX_EXECUTION_DATE='2024-08-21T04:03:56.076722+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-21T04:03:56.076722+00:00'
[2024-08-21T04:07:47.678+0000] {logging_mixin.py:188} WARNING -   0%|          | 0/4 [00:00<?, ?it/s]
[2024-08-21T04:07:47.680+0000] {logging_mixin.py:188} WARNING - 100%|##########| 4/4 [00:00<00:00, 31595.51it/s]
[2024-08-21T04:08:07.126+0000] {logging_mixin.py:188} WARNING -   0%|          | 0/11 [00:00<?, ?it/s]
[2024-08-21T04:08:07.128+0000] {logging_mixin.py:188} WARNING - 100%|##########| 11/11 [00:00<00:00, 58034.39it/s]
[2024-08-21T04:08:25.220+0000] {logging_mixin.py:188} WARNING -   0%|          | 0/24 [00:00<?, ?it/s]
[2024-08-21T04:08:25.221+0000] {logging_mixin.py:188} WARNING - 100%|##########| 24/24 [00:00<00:00, 100562.73it/s]
[2024-08-21T04:08:29.396+0000] {logging_mixin.py:188} WARNING -   0%|          | 0/24 [00:00<?, ?it/s]
[2024-08-21T04:08:29.398+0000] {logging_mixin.py:188} WARNING - 100%|##########| 24/24 [00:00<00:00, 79512.87it/s]
[2024-08-21T04:08:34.053+0000] {logging_mixin.py:188} WARNING -   0%|          | 0/4 [00:00<?, ?it/s]
[2024-08-21T04:08:34.054+0000] {logging_mixin.py:188} WARNING - 100%|##########| 4/4 [00:00<00:00, 31242.49it/s]
[2024-08-21T04:08:38.733+0000] {logging_mixin.py:188} WARNING -   0%|          | 0/4 [00:00<?, ?it/s]
[2024-08-21T04:08:38.734+0000] {logging_mixin.py:188} WARNING - 100%|##########| 4/4 [00:00<00:00, 33756.97it/s]
[2024-08-21T04:09:02.035+0000] {logging_mixin.py:188} WARNING -   0%|          | 0/1 [00:00<?, ?it/s]
[2024-08-21T04:09:02.036+0000] {logging_mixin.py:188} WARNING - 100%|##########| 1/1 [00:00<00:00, 11275.01it/s]
[2024-08-21T04:09:09.329+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/components/vehicle/data_scraping_components/post_links_extraction.py", line 68, in scrape_links
    upload_table('ikman_vehicle_post_links')
  File "/opt/airflow/dags/components/utils/database_table_creation.py", line 29, in upload_table
    cur.execute(f"""
psycopg2.errors.InsufficientPrivilege: could not open file "/var/lib/postgresql/csv/ikman_vehicle_post_links.csv" for writing: Permission denied
HINT:  COPY TO instructs the PostgreSQL server process to write a file. You may want a client-side facility such as psql's \copy.

[2024-08-21T04:09:09.355+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=Vehicle_Data_scrape_Pipeline_5, task_id=scrape_post_links, execution_date=20240821T040356, start_date=20240821T040746, end_date=20240821T040909
[2024-08-21T04:09:09.359+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:207 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2024-08-21T04:09:09.363+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/email.py:154 RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2024-08-21T04:09:09.364+0000] {email.py:270} INFO - Email alerting: attempt 1
[2024-08-21T04:09:11.084+0000] {email.py:281} INFO - Sent an alert email to ['deshanariyarathna@gmail.com']
[2024-08-21T04:09:12.978+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 16 for task scrape_post_links (could not open file "/var/lib/postgresql/csv/ikman_vehicle_post_links.csv" for writing: Permission denied
HINT:  COPY TO instructs the PostgreSQL server process to write a file. You may want a client-side facility such as psql's \copy.
; 681)
[2024-08-21T04:09:13.007+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-08-21T04:09:13.024+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
