[2024-08-22T06:41:55.909+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Vehicle_Data_scrape_Pipeline_2.scrape_vehicle_info_from_link manual__2024-08-22T06:41:15.580113+00:00 [queued]>
[2024-08-22T06:41:55.919+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Vehicle_Data_scrape_Pipeline_2.scrape_vehicle_info_from_link manual__2024-08-22T06:41:15.580113+00:00 [queued]>
[2024-08-22T06:41:55.920+0000] {taskinstance.py:2193} INFO - Starting attempt 3 of 4
[2024-08-22T06:41:55.935+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): scrape_vehicle_info_from_link> on 2024-08-22 06:41:15.580113+00:00
[2024-08-22T06:41:55.941+0000] {standard_task_runner.py:60} INFO - Started process 3153 to run task
[2024-08-22T06:41:55.943+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Vehicle_Data_scrape_Pipeline_2', 'scrape_vehicle_info_from_link', 'manual__2024-08-22T06:41:15.580113+00:00', '--job-id', '120', '--raw', '--subdir', 'DAGS_FOLDER/vehicle_data_scraping_pipeline.py', '--cfg-path', '/tmp/tmpr2p3p2mv']
[2024-08-22T06:41:55.946+0000] {standard_task_runner.py:88} INFO - Job 120: Subtask scrape_vehicle_info_from_link
[2024-08-22T06:41:55.998+0000] {task_command.py:423} INFO - Running <TaskInstance: Vehicle_Data_scrape_Pipeline_2.scrape_vehicle_info_from_link manual__2024-08-22T06:41:15.580113+00:00 [running]> on host 84a0d27b37bd
[2024-08-22T06:41:56.176+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='sdeshan' AIRFLOW_CTX_DAG_ID='Vehicle_Data_scrape_Pipeline_2' AIRFLOW_CTX_TASK_ID='scrape_vehicle_info_from_link' AIRFLOW_CTX_EXECUTION_DATE='2024-08-22T06:41:15.580113+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-22T06:41:15.580113+00:00'
[2024-08-22T06:41:56.184+0000] {logging_mixin.py:188} WARNING - 0it [00:00, ?it/s]
[2024-08-22T06:41:56.185+0000] {logging_mixin.py:188} WARNING - 0it [00:00, ?it/s]
[2024-08-22T06:41:56.193+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/components/vehicle/data_scraping_components/post_data_extraction.py", line 154, in scarpe_and_save
    populate_table(data_table, car_df)
  File "/opt/airflow/dags/components/utils/database_table_creation.py", line 43, in populate_table
    data_tuples = [tuple(x) for x in data.to_records(index=False)]
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/frame.py", line 2479, in to_records
    return np.rec.fromarrays(arrays, dtype={"names": names, "formats": formats})
  File "/home/airflow/.local/lib/python3.8/site-packages/numpy/core/records.py", line 643, in fromarrays
    shape = arrayList[0].shape
IndexError: list index out of range
[2024-08-22T06:41:56.232+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=Vehicle_Data_scrape_Pipeline_2, task_id=scrape_vehicle_info_from_link, execution_date=20240822T064115, start_date=20240822T064155, end_date=20240822T064156
[2024-08-22T06:41:56.242+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 120 for task scrape_vehicle_info_from_link (list index out of range; 3153)
[2024-08-22T06:41:56.278+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-08-22T06:41:56.294+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
