[2024-10-21T04:29:17.644+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Gold_training_Pipeline.model_training scheduled__2024-10-15T00:00:00+00:00 [queued]>
[2024-10-21T04:29:17.655+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Gold_training_Pipeline.model_training scheduled__2024-10-15T00:00:00+00:00 [queued]>
[2024-10-21T04:29:17.656+0000] {taskinstance.py:2193} INFO - Starting attempt 2 of 4
[2024-10-21T04:29:17.861+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): model_training> on 2024-10-15 00:00:00+00:00
[2024-10-21T04:29:17.868+0000] {standard_task_runner.py:60} INFO - Started process 515 to run task
[2024-10-21T04:29:17.879+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Gold_training_Pipeline', 'model_training', 'scheduled__2024-10-15T00:00:00+00:00', '--job-id', '79', '--raw', '--subdir', 'DAGS_FOLDER/gold_training_pipeline.py', '--cfg-path', '/tmp/tmpgexe6o6r']
[2024-10-21T04:29:17.884+0000] {standard_task_runner.py:88} INFO - Job 79: Subtask model_training
[2024-10-21T04:29:18.204+0000] {task_command.py:423} INFO - Running <TaskInstance: Gold_training_Pipeline.model_training scheduled__2024-10-15T00:00:00+00:00 [running]> on host e58a92ba783e
[2024-10-21T04:29:18.294+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='sdeshan' AIRFLOW_CTX_DAG_ID='Gold_training_Pipeline' AIRFLOW_CTX_TASK_ID='model_training' AIRFLOW_CTX_EXECUTION_DATE='2024-10-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-15T00:00:00+00:00'
[2024-10-21T04:29:18.527+0000] {filesystem.py:118} DEBUG - input tempfile: /tmp/tmp24idms4z/xt2_fcnu.json
[2024-10-21T04:29:19.125+0000] {filesystem.py:118} DEBUG - input tempfile: /tmp/tmp24idms4z/udsrwmt6.json
[2024-10-21T04:29:19.126+0000] {model.py:2042} DEBUG - idx 0
[2024-10-21T04:29:19.127+0000] {model.py:2043} DEBUG - running CmdStan, num_threads: None
[2024-10-21T04:29:19.128+0000] {model.py:2055} DEBUG - CmdStan args: ['/home/***/.local/lib/python3.8/site-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=57502', 'data', 'file=/tmp/tmp24idms4z/xt2_fcnu.json', 'init=/tmp/tmp24idms4z/udsrwmt6.json', 'output', 'file=/tmp/tmp24idms4z/prophet_modelciueq9hh/prophet_model-20241021042919.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
[2024-10-21T04:29:19.128+0000] {logging_mixin.py:188} WARNING - 04:29:19 - cmdstanpy - INFO - Chain [1] start processing
[2024-10-21T04:29:19.128+0000] {model.py:2058} INFO - Chain [1] start processing
[2024-10-21T04:29:58.395+0000] {logging_mixin.py:188} WARNING - 04:29:58 - cmdstanpy - INFO - Chain [1] done processing
[2024-10-21T04:29:58.395+0000] {model.py:2115} INFO - Chain [1] done processing
[2024-10-21T04:30:11.231+0000] {logging_mixin.py:188} INFO - Fitting 3 folds for each of 1 candidates, totalling 3 fits
[2024-10-21T04:34:16.649+0000] {local_task_job_runner.py:302} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2024-10-21T04:34:16.695+0000] {process_utils.py:131} INFO - Sending 15 to group 515. PIDs of all processes in the group: [515]
[2024-10-21T04:34:16.705+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 515
[2024-10-21T04:34:20.621+0000] {taskinstance.py:2483} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-10-21T04:34:20.666+0000] {logging_mixin.py:188} INFO - [CV] END learning_rate=0.001, max_depth=10, min_child_weight=1, n_estimators=500; total time= 4.2min
[2024-10-21T04:35:16.739+0000] {process_utils.py:149} WARNING - process psutil.Process(pid=515, name='airflow task ru', status='running', started='04:29:17') did not respond to SIGTERM. Trying SIGKILL
[2024-10-21T04:35:16.806+0000] {process_utils.py:86} INFO - Sending the signal 9 to group 515
[2024-10-21T04:35:16.864+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=515, name='airflow task ru', status='terminated', exitcode=<Negsignal.SIGKILL: -9>, started='04:29:17') (515) terminated with exit code -9
[2024-10-21T04:35:16.866+0000] {standard_task_runner.py:175} ERROR - Job 79 was killed before it finished (likely due to running out of memory)
