[2024-08-27T08:24:25.335+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Gold_News_pipeline.scrape_gold_news manual__2024-08-27T08:24:13.945584+00:00 [queued]>
[2024-08-27T08:24:25.342+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Gold_News_pipeline.scrape_gold_news manual__2024-08-27T08:24:13.945584+00:00 [queued]>
[2024-08-27T08:24:25.343+0000] {taskinstance.py:2193} INFO - Starting attempt 2 of 4
[2024-08-27T08:24:25.355+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): scrape_gold_news> on 2024-08-27 08:24:13.945584+00:00
[2024-08-27T08:24:25.360+0000] {standard_task_runner.py:60} INFO - Started process 4276 to run task
[2024-08-27T08:24:25.362+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Gold_News_pipeline', 'scrape_gold_news', 'manual__2024-08-27T08:24:13.945584+00:00', '--job-id', '229', '--raw', '--subdir', 'DAGS_FOLDER/gold_news_pipeline.py', '--cfg-path', '/tmp/tmpy72c9hb2']
[2024-08-27T08:24:25.364+0000] {standard_task_runner.py:88} INFO - Job 229: Subtask scrape_gold_news
[2024-08-27T08:24:25.407+0000] {task_command.py:423} INFO - Running <TaskInstance: Gold_News_pipeline.scrape_gold_news manual__2024-08-27T08:24:13.945584+00:00 [running]> on host 6c6a25447d9d
[2024-08-27T08:24:25.572+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='sdeshan' AIRFLOW_CTX_DAG_ID='Gold_News_pipeline' AIRFLOW_CTX_TASK_ID='scrape_gold_news' AIRFLOW_CTX_EXECUTION_DATE='2024-08-27T08:24:13.945584+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-27T08:24:13.945584+00:00'
[2024-08-27T08:24:28.924+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/components/gold/news_scraping/post_links_extraction.py", line 47, in scrape_gold_news_urls
    upload_table("gold_news_urls")
  File "/opt/airflow/dags/components/utils/database_table_creation.py", line 29, in upload_table
    cur.execute(f"""
psycopg2.errors.InsufficientPrivilege: could not open file "/var/lib/postgresql/gold/gold_news_urls.csv" for writing: Permission denied
HINT:  COPY TO instructs the PostgreSQL server process to write a file. You may want a client-side facility such as psql's \copy.

[2024-08-27T08:24:28.961+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=Gold_News_pipeline, task_id=scrape_gold_news, execution_date=20240827T082413, start_date=20240827T082425, end_date=20240827T082428
[2024-08-27T08:24:28.971+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 229 for task scrape_gold_news (could not open file "/var/lib/postgresql/gold/gold_news_urls.csv" for writing: Permission denied
HINT:  COPY TO instructs the PostgreSQL server process to write a file. You may want a client-side facility such as psql's \copy.
; 4276)
[2024-08-27T08:24:29.000+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-08-27T08:24:29.014+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
