[2024-08-22T05:05:27.225+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Vehicle_Data_scrape_Pipeline_5.scrape_post_links scheduled__2024-08-21T00:00:00+00:00 [queued]>
[2024-08-22T05:05:27.231+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Vehicle_Data_scrape_Pipeline_5.scrape_post_links scheduled__2024-08-21T00:00:00+00:00 [queued]>
[2024-08-22T05:05:27.232+0000] {taskinstance.py:2193} INFO - Starting attempt 3 of 4
[2024-08-22T05:05:27.245+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): scrape_post_links> on 2024-08-21 00:00:00+00:00
[2024-08-22T05:05:27.249+0000] {standard_task_runner.py:60} INFO - Started process 860 to run task
[2024-08-22T05:05:27.251+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Vehicle_Data_scrape_Pipeline_5', 'scrape_post_links', 'scheduled__2024-08-21T00:00:00+00:00', '--job-id', '86', '--raw', '--subdir', 'DAGS_FOLDER/vehicle_data_scraping_pipeline.py', '--cfg-path', '/tmp/tmp_cqkruz3']
[2024-08-22T05:05:27.253+0000] {standard_task_runner.py:88} INFO - Job 86: Subtask scrape_post_links
[2024-08-22T05:05:27.285+0000] {task_command.py:423} INFO - Running <TaskInstance: Vehicle_Data_scrape_Pipeline_5.scrape_post_links scheduled__2024-08-21T00:00:00+00:00 [running]> on host b761e1bbb455
[2024-08-22T05:05:27.422+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='sdeshan' AIRFLOW_CTX_DAG_ID='Vehicle_Data_scrape_Pipeline_5' AIRFLOW_CTX_TASK_ID='scrape_post_links' AIRFLOW_CTX_EXECUTION_DATE='2024-08-21T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-21T00:00:00+00:00'
[2024-08-22T05:06:38.415+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/components/vehicle/data_scraping_components/post_links_extraction.py", line 68, in scrape_links
    upload_table('ikman_vehicle_post_links')
  File "/opt/airflow/dags/components/utils/database_table_creation.py", line 29, in upload_table
    cur.execute(f"""
psycopg2.errors.InsufficientPrivilege: could not open file "/var/lib/postgresql/csv/ikman_vehicle_post_links.csv" for writing: Permission denied
HINT:  COPY TO instructs the PostgreSQL server process to write a file. You may want a client-side facility such as psql's \copy.

[2024-08-22T05:06:38.444+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=Vehicle_Data_scrape_Pipeline_5, task_id=scrape_post_links, execution_date=20240821T000000, start_date=20240822T050527, end_date=20240822T050638
[2024-08-22T05:06:38.453+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 86 for task scrape_post_links (could not open file "/var/lib/postgresql/csv/ikman_vehicle_post_links.csv" for writing: Permission denied
HINT:  COPY TO instructs the PostgreSQL server process to write a file. You may want a client-side facility such as psql's \copy.
; 860)
[2024-08-22T05:06:38.471+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-08-22T05:06:38.486+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
